apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: booking
data:
  SPRING_CACHE_TYPE: redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  BOOKING_KAFKA_ENABLED: "true"
  BOOKING_HOTEL_EVENTS_TOPIC: hotel-events
  OTEL_TRACES_ENDPOINT: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
