apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: booking
type: Opaque
stringData:
  BOOKING_USER_USERNAME: user
  BOOKING_USER_PASSWORD: change-me-user
  BOOKING_ADMIN_USERNAME: admin
  BOOKING_ADMIN_PASSWORD: change-me-admin
