apiVersion: v1
kind: Secret
metadata:
  name: mini-risk-secrets
  namespace: mini-risk
type: Opaque
stringData:
  POSTGRES_USER: risk
  POSTGRES_PASSWORD: risk
  SPRING_DATASOURCE_USERNAME: risk
  SPRING_DATASOURCE_PASSWORD: risk
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin

