package dev.interview.ledger;
import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.OffsetDateTime;import java.util.*;
@Service public class ExternalImportService{
 private final JdbcTemplate db;private final ReconciliationService rec;private final ObjectMapper json;ExternalImportService(JdbcTemplate d,ReconciliationService r,ObjectMapper j){db=d;rec=r;json=j;}
 @Transactional public Map<String,Object> ingest(ApiModels.ExternalFile file){String raw;try{raw=json.writeValueAsString(file);}catch(Exception e){throw new IllegalStateException(e);}String hash=Hashing.sha256(raw);var old=db.queryForList("select * from external_imports where file_hash=?",hash);if(!old.isEmpty())return Map.of("importId",old.getFirst().get("ID"),"status","DUPLICATE_FILE","accepted",old.getFirst().get("ACCEPTED_ROWS"),"quarantined",old.getFirst().get("QUARANTINED_ROWS"));String id="imp_"+UUID.randomUUID().toString().substring(0,12);int accepted=0,bad=0,rowNo=0;for(var row:file.rows()){rowNo++;try{if(!"v1".equals(file.schemaVersion()))throw new IllegalArgumentException("UNSUPPORTED_SCHEMA_VERSION");String external=required(row,"externalId"),key=required(row,"matchKey"),currency=required(row,"currency"),status=required(row,"status");Object amount=row.get("amount");if(!(amount instanceof Number))throw new IllegalArgumentException("AMOUNT_NOT_NUMERIC");rec.importExternal(new ApiModels.ImportExternal(external,key,((Number)amount).longValue(),currency,status));accepted++;}catch(Exception e){bad++;quarantine(id,rowNo,row,e);}}
 String status=bad==0?"IMPORTED":accepted==0?"ERROR_FATAL":"IMPORTED_WITH_QUARANTINE";db.update("insert into external_imports values(?,?,?,?,?,?,?,?,?)",id,"STRIPE",file.fileName(),hash,file.schemaVersion(),status,accepted,bad,OffsetDateTime.now());return Map.of("importId",id,"status",status,"accepted",accepted,"quarantined",bad);}
 private String required(Map<String,Object>r,String k){Object v=r.get(k);if(v==null||v.toString().isBlank())throw new IllegalArgumentException("MISSING_"+k.toUpperCase());return v.toString();}private void quarantine(String id,int n,Map<String,Object>row,Exception e){String raw;try{raw=json.writeValueAsString(row);}catch(Exception x){raw="{}";}db.update("insert into quarantined_external_rows values(?,?,?,?,?,?,?)","q_"+UUID.randomUUID().toString().substring(0,12),id,n,raw,"SCHEMA_DRIFT",e.getMessage(),OffsetDateTime.now());}
 public List<Map<String,Object>>imports(){return db.queryForList("select * from external_imports order by created_at desc");}public List<Map<String,Object>>quarantine(){return db.queryForList("select * from quarantined_external_rows order by created_at desc");}
}
