package dev.interview.agent.tools;
import dev.interview.agent.llm.LlmClient.Action; import org.springframework.stereotype.Component; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.Duration; import java.util.*; import java.util.concurrent.*; import java.util.stream.*;
@Component public class ToolExecutor {
 private static final Set<String> ALLOWED=Set.of("list_files","read_file","write_file","search_text","run_command","git_status","git_diff","run_build","run_tests","create_branch","create_commit","create_pull_request"); private static final Set<String> COMMANDS=Set.of("git","./gradlew","./mvnw","npm","pnpm");
 public ToolResult execute(Path root,String sandbox,Action a,Duration timeout){if(!ALLOWED.contains(a.tool()))return fail("tool not allowed");long started=System.nanoTime();try{String out=switch(a.tool()){case"list_files"->list(safe(root,arg(a,"path",".")));case"read_file"->Files.readString(safe(root,arg(a,"path",null)));case"write_file"->write(safe(root,arg(a,"path",null)),arg(a,"content",""));case"search_text"->search(safe(root,arg(a,"path",".")),arg(a,"query",null));case"git_status"->inside(sandbox,List.of("git","status","--short"),timeout);case"git_diff"->inside(sandbox,List.of("git","diff","--no-ext-diff"),timeout);case"run_build"->auto(root,sandbox,true,timeout);case"run_tests"->auto(root,sandbox,false,timeout);case"create_branch"->inside(sandbox,List.of("git","switch","-c",arg(a,"name",null)),timeout);case"create_commit"->inside(sandbox,List.of("git","commit","-am",arg(a,"message","agent change")),timeout);case"run_command"->validated(sandbox,arg(a,"command",null),timeout);case"create_pull_request"->"PR adapter requires GitHub App credentials; no remote mutation performed";default->throw new IllegalArgumentException();};return new ToolResult(true,redact(out),ms(started));}catch(Exception e){return new ToolResult(false,redact(e.getMessage()),ms(started));}}
 private String arg(Action a,String k,String d){String v=a.arguments().get(k);if(v==null&&d==null)throw new IllegalArgumentException("missing "+k);return v==null?d:v;} private Path safe(Path root,String rel){Path p=root.resolve(rel).normalize();if(!p.startsWith(root.normalize()))throw new SecurityException("path traversal blocked");return p;}
 private String list(Path p)throws Exception{try(Stream<Path>s=Files.walk(p,4)){return s.filter(Files::isRegularFile).limit(500).map(p::relativize).map(Path::toString).collect(Collectors.joining("\n"));}} private String write(Path p,String c)throws Exception{Files.createDirectories(p.getParent());Files.writeString(p,c);return"wrote "+p.getFileName();}
 private String search(Path p,String q)throws Exception{try(Stream<Path>s=Files.walk(p,5)){return s.filter(Files::isRegularFile).flatMap(f->{try{return Files.lines(f).filter(x->x.contains(q)).limit(20).map(x->p.relativize(f)+": "+x);}catch(Exception e){return Stream.empty();}}).limit(100).collect(Collectors.joining("\n"));}}
 private String validated(String box,String raw,Duration t)throws Exception{if(raw.matches("(?s).*(;|&&|\\|\\||`|\\$\\(|>|<).*"))throw new SecurityException("shell operators blocked");List<String> p=Arrays.asList(raw.trim().split("\\s+"));if(p.isEmpty()||!COMMANDS.contains(p.get(0)))throw new SecurityException("executable not allowed");return inside(box,p,t);}
 private String auto(Path r,String box,boolean build,Duration t)throws Exception{if(Files.exists(r.resolve("gradlew")))return inside(box,List.of("./gradlew",build?"build":"test","--no-daemon"),t);if(Files.exists(r.resolve("mvnw")))return inside(box,List.of("./mvnw",build?"package":"test","-B"),t);if(Files.exists(r.resolve("package.json")))return inside(box,build?List.of("npm","run","build"):List.of("npm","test","--","--run"),t);return"no recognized build system";}
 private String inside(String box,List<String> cmd,Duration t)throws Exception{List<String> all=new ArrayList<>(List.of("docker","exec",box));all.addAll(cmd);Process p=new ProcessBuilder(all).redirectErrorStream(true).start();if(!p.waitFor(t.toMillis(),TimeUnit.MILLISECONDS)){p.destroyForcibly();throw new TimeoutException("command timed out");}String out=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(p.exitValue()!=0)throw new IllegalStateException("exit="+p.exitValue()+" "+out);return out;}
 private String redact(String s){return s==null?"":s.replaceAll("(?i)(token|password|secret|api[_-]?key)[=: ]+\\S+","$1=[REDACTED]");}private long ms(long s){return TimeUnit.NANOSECONDS.toMillis(System.nanoTime()-s);}private ToolResult fail(String x){return new ToolResult(false,x,0);}public record ToolResult(boolean success,String output,long durationMs){}
}
