package dev.interview.agent.sandbox;
import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Duration;import java.util.*;import java.util.concurrent.TimeUnit;
@Component public class SandboxManager{
 private final Path base;private final String image;public SandboxManager(@Value("${agent.workspace-root:./workspaces}")String base,@Value("${agent.sandbox-image:cloud-agent-sandbox:local}")String image){this.base=Path.of(base).toAbsolutePath();this.image=image;}
 public Sandbox allocate(UUID id,String repo,String branch)throws Exception{validateRepo(repo);Path dir=base.resolve(id.toString());Files.createDirectories(dir);String name="agent-"+id;String work="/workspaces/"+id;run(List.of("docker","run","-d","--name",name,"--user","10001:10001","--cpus","1","--memory","1g","--pids-limit","256","--network","bridge","--read-only","--tmpfs","/tmp:rw,noexec,nosuid,size=128m","--volumes-from","cloud-agent-backend","--workdir",work,image,"sleep","3600"),Duration.ofMinutes(2));List<String> clone=new ArrayList<>(List.of("docker","exec",name,"git","clone","--depth","1"));if(branch!=null&&!branch.isBlank())Collections.addAll(clone,"--branch",branch);clone.add(repo);clone.add(work);run(clone,Duration.ofMinutes(3));return new Sandbox(name,dir);}
 public boolean cleanup(Sandbox s){try{run(List.of("docker","rm","-f",s.name()),Duration.ofSeconds(20));return true;}catch(Exception e){return false;}}
 private void validateRepo(String r){if(!r.matches("https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+(?:\\.git)?"))throw new IllegalArgumentException("only GitHub HTTPS repositories are allowed");}
 private String run(List<String> c,Duration t)throws Exception{Process p=new ProcessBuilder(c).redirectErrorStream(true).start();if(!p.waitFor(t.toMillis(),TimeUnit.MILLISECONDS)){p.destroyForcibly();throw new IllegalStateException("sandbox timeout");}String o=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(p.exitValue()!=0)throw new IllegalStateException(o);return o;}public record Sandbox(String name,Path workspace){}
}
