package dev.interview.agent.session;
import jakarta.persistence.*; import java.time.Instant; import java.util.*;
@Entity @Table(name="agent_sessions") public class AgentSession {
 @Id private UUID id; @Column(nullable=false) private String ownerId; @Column(nullable=false,length=1000) private String repositoryUrl; private String branchName;
 @Column(nullable=false,length=10000) private String task; @Enumerated(EnumType.STRING) private SessionState state; @Column(length=20000) private String plan; @Column(length=100000) private String finalDiff; @Column(length=20000) private String summary; private String stopReason; private boolean cleanupSucceeded; private int llmCalls; private long inputTokens; private long outputTokens; private Instant createdAt; private Instant updatedAt; @Version private long version;
 protected AgentSession(){} public AgentSession(UUID id,String owner,String repo,String branch,String task,Instant now){this.id=id;ownerId=owner;repositoryUrl=repo;branchName=branch;this.task=task;state=SessionState.CREATED;createdAt=updatedAt=now;}
 public UUID getId(){return id;} public String getOwnerId(){return ownerId;} public String getRepositoryUrl(){return repositoryUrl;} public String getBranchName(){return branchName;} public String getTask(){return task;} public SessionState getState(){return state;} public String getPlan(){return plan;} public String getFinalDiff(){return finalDiff;} public String getSummary(){return summary;} public String getStopReason(){return stopReason;} public boolean isCleanupSucceeded(){return cleanupSucceeded;} public int getLlmCalls(){return llmCalls;} public long getInputTokens(){return inputTokens;} public long getOutputTokens(){return outputTokens;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;}
 public void transition(SessionState next,Instant now){if(state.terminal())throw new IllegalStateException("terminal session"); state=next;updatedAt=now;} public void plan(String p){plan=p;} public void complete(String diff,String s,Instant now){finalDiff=diff;summary=s;transition(SessionState.COMPLETED,now);} public void fail(String why,Instant now){stopReason=why;transition(SessionState.FAILED,now);} public void cancel(Instant now){stopReason="cancelled by user";transition(SessionState.CANCELLED,now);} public void cleanup(boolean ok){cleanupSucceeded=ok;} public void usage(int calls,long in,long out){llmCalls+=calls;inputTokens+=in;outputTokens+=out;}
}
