server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

services:
  order-service:
    base-url: ${ORDER_SERVICE_URL:http://localhost:8081}
  history-service:
    base-url: ${HISTORY_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

