FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/distributed-database-0.1.0-SNAPSHOT.jar /app/distributed-db.jar
ENTRYPOINT ["java", "-jar", "/app/distributed-db.jar"]
