server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: ride-sharing-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/rideshare}
    username: ${SPRING_DATASOURCE_USERNAME:capstone}
    password: ${SPRING_DATASOURCE_PASSWORD:capstone}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
