server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        ptr.order.latency: true

spring:
  application:
    name: pretrade-risk-engine
