import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,BookOpen,CheckCircle2,CircleDollarSign,Database,RefreshCw,Search,ShieldAlert,Webhook}from'lucide-react';
import'./style.css';

const api=async(path:string,options:any={})=>{const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok)throw new Error((await r.json()).error||r.statusText);return r.status===202?null:r.json()};
const money=(n:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format((n||0)/100);
const badge=(s:string)=><span className={'badge '+(s?.includes('MATCHED')||s==='CAPTURED'?'ok':s?.includes('FAIL')||s==='MISMATCHED'?'bad':'warn')}>{s}</span>;

function App(){
 const[payments,setPayments]=useState<any[]>([]),[balances,setBalances]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[support,setSupport]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const[p,b,r]=await Promise.all([api('/payments'),api('/balances'),api('/reconciliations')]);setPayments(p);setBalances(b);setRuns(r);if(r[0])setSelected(await api('/reconciliations/'+r[0].ID));};
 useEffect(()=>{load().catch(()=>setNotice('Seed the demo to begin.'));const timer=setInterval(()=>load().catch(()=>{}),2000);return()=>clearInterval(timer)},[]);
 const seed=async()=>{setBusy(true);try{await api('/demo/reset-and-seed',{method:'POST'});await load();setNotice('Deterministic failure scenarios seeded.');}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const inspect=async(id:string)=>setSupport(await api('/support/payments/'+id));
 const matched=selected?.items?.filter((x:any)=>x.STATE==='MATCHED').length||0,mismatch=selected?.items?.filter((x:any)=>x.STATE==='MISMATCHED').length||0;
 return <div className="shell">
  <aside><div className="brand"><span>SL</span><div>Stripe Ledger<small>RECONCILIATION LAB</small></div></div><nav><a className="active"><Activity/>Command center</a><a><CircleDollarSign/>Payments</a><a><BookOpen/>Ledger</a><a><RefreshCw/>Reconciliation</a><a><Webhook/>Event inbox</a></nav><div className="system"><i></i> LOCAL SYSTEM HEALTHY<small>Append-only ledger · H2/Postgres</small></div></aside>
  <main><header><div><p className="eyebrow">OPERATIONS / DAILY CLOSE</p><h1>Money movement, explained.</h1><p>Trace every retry, event, journal, and settlement delta to its source.</p></div><button onClick={seed} disabled={busy}><RefreshCw className={busy?'spin':''}/>{busy?'Seeding…':'Reset & run demo'}</button></header>
  {notice&&<div className="notice">{notice}</div>}
  <section className="stats"><article><label>Payments</label><strong>{payments.length}</strong><small>Across idempotent requests</small></article><article><label>Projected accounts</label><strong>{balances.length}</strong><small>Read model &lt;200ms target</small></article><article><label>Matched keys</label><strong>{matched}</strong><small>Internal = processor</small></article><article className="danger"><label>Needs explanation</label><strong>{mismatch}</strong><small>Deterministic reason codes</small></article></section>
  <div className="grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">PAYMENT LIFECYCLE</p><h2>Recent payments</h2></div><ShieldAlert/></div><table><thead><tr><th>Customer / order</th><th>Stripe objects</th><th>Amount</th><th>State</th><th></th></tr></thead><tbody>{payments.map(p=><tr key={p.ID}><td><b>{p.CUSTOMER_ID}</b><small>{p.ORDER_ID}</small></td><td><code>{p.STRIPE_PAYMENT_INTENT_ID}</code><small>{p.STRIPE_CHARGE_ID}</small></td><td>{money(p.AMOUNT,p.CURRENCY)}</td><td>{badge(p.STATUS)}</td><td><button className="icon" onClick={()=>inspect(p.ID)}><Search/></button></td></tr>)}</tbody></table></section>
  <section className="panel balances"><div className="panel-head"><div><p className="eyebrow">CURRENT VIEW</p><h2>Account balances</h2></div><Database/></div>{balances.map(b=><div className="balance" key={b.ACCOUNT_ID+b.CURRENCY}><div><b>{b.ACCOUNT_ID.replaceAll('_',' ')}</b><small>v{b.VERSION} · {b.CURRENCY}</small></div><strong>{money(b.BALANCE,b.CURRENCY)}</strong></div>)}</section></div>
  <section className="panel reconcile"><div className="panel-head"><div><p className="eyebrow">DETERMINISTIC COMPARISON</p><h2>Latest reconciliation</h2>{selected?.shards&&<small>{selected.shards.filter((s:any)=>s.STATUS==='COMPLETED').length}/{selected.shards.length} durable shards complete</small>}</div>{selected&&badge(selected.STATUS)}</div>{!selected?<div className="empty">Run the demo to produce a daily reconciliation.</div>:<table><thead><tr><th>Stable match key</th><th>Internal</th><th>Stripe</th><th>Delta</th><th>Explanation</th></tr></thead><tbody>{selected.items.map((i:any)=><tr key={i.MATCH_KEY}><td><code>{i.MATCH_KEY}</code></td><td>{money(i.INTERNAL_SUM,i.CURRENCY)}</td><td>{money(i.EXTERNAL_SUM,i.CURRENCY)}</td><td className={i.DELTA?'red':''}>{money(i.DELTA,i.CURRENCY)}</td><td>{badge(i.STATE)} <small className="reason">{i.REASON}</small></td></tr>)}</tbody></table>}</section>
  </main>
  {support&&<div className="modal" onClick={()=>setSupport(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSupport(null)}>×</button><p className="eyebrow">SUPPORT EXPLAINER</p><h2>Why was this customer charged?</h2><div className="answer"><CheckCircle2/>One logical payment maps to <b>{support.payment.STRIPE_PAYMENT_INTENT_ID}</b>. Retries sharing the key return the stored response; no second journal is posted. Duplicate-charge candidates found: <b>{support.possibleDuplicateCharges.length}</b>.</div><h3>Immutable money trail</h3>{support.ledgerEntries.map((e:any)=><div className="timeline"><i></i><div><b>{e.ENTRY_TYPE}</b><code>{e.JOURNAL_ID}</code><p>{e.ACCOUNT_ID}: {money(e.AMOUNT,e.CURRENCY)}</p><small>Stripe: {e.STRIPE_OBJECT_ID}</small></div></div>)}<h3>Webhook evidence</h3>{support.webhooks.map((w:any)=><div className="event"><code>{w.EVENT_ID}</code>{badge(w.STATUS)}<small>{w.EVENT_TYPE} · {w.NOTE}</small></div>)}</div></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
