FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /src
COPY . .
RUN mvn -q -pl engine -am package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /src/common/target/exchange-lite-common-0.1.0.jar /app/
COPY --from=build /src/engine/target/exchange-lite-engine-0.1.0.jar /app/
EXPOSE 9090 9191
ENTRYPOINT ["java", "-cp", "/app/*", "io.exchangelite.engine.app.EngineApplication"]
