server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: url-shortener
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME:capstone}
    password: ${SPRING_DATASOURCE_PASSWORD:capstone}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
