package com.interview.fraud.ai;
import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import com.interview.fraud.casework.*; import com.interview.fraud.platform.AuditService; import java.time.Instant; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AiInvestigationService {private final CaseWorkflowService cases;private final ApprovedToolRegistry tools;private final PolicyRagService rag;private final JdbcTemplate jdbc;private final AuditService audit;private final ObjectMapper json;private final AgentSecurityService security;public AiInvestigationService(CaseWorkflowService c,ApprovedToolRegistry t,PolicyRagService r,JdbcTemplate j,AuditService a,ObjectMapper o,AgentSecurityService s){cases=c;tools=t;rag=r;jdbc=j;audit=a;json=o;security=s;}
 @Transactional public InvestigationResult investigate(UUID caseId,String actor){return investigate(caseId,actor,null);} @Transactional public InvestigationResult investigate(UUID caseId,String actor,AgentSecurityService.InvestigationRequest request){CaseEntity c=cases.require(caseId);var inspection=security.inspect(caseId,actor,request);if(inspection.blocked())throw new SecurityException(inspection.decision()+": "+inspection.reason());UUID investigation=UUID.randomUUID();jdbc.update("INSERT INTO ai_investigations(id,case_id,model,prompt_masked,response_json,valid,created_at) VALUES(?,?,?,?,?,true,?)",investigation,caseId,"mock-structured-v1","System prompt + masked evidence","{}",Instant.now());List<InvestigationResult.Evidence> evidence=new ArrayList<>();for(String tool:List.of("getTransactionDetails","getTransactionHistory","getDeviceHistory","getMerchantRiskProfile","calculateRiskScore")){try{Object result=tools.call(tool,c,actor);evidence.add(new InvestigationResult.Evidence(tool,safeJson(result)));jdbc.update("INSERT INTO ai_tool_calls(id,investigation_id,tool_name,arguments_masked,result_masked,success,created_at) VALUES(?,?,?,?,?,true,?)",UUID.randomUUID(),investigation,tool,"{caseId:MASKED}",safeJson(result),Instant.now());}catch(RuntimeException ex){jdbc.update("INSERT INTO ai_tool_calls(id,investigation_id,tool_name,arguments_masked,result_masked,success,created_at) VALUES(?,?,?,?,?,false,?)",UUID.randomUUID(),investigation,tool,"{}",ex.getClass().getSimpleName(),Instant.now());}}
 var signals=cases.signals(caseId);var citations=rag.search(signals.toString());String action=c.deterministicScore>=70?"ESCALATE_AND_HOLD":c.deterministicScore>=40?"MANUAL_REVIEW":"APPROVE";var result=new InvestigationResult("Deterministic signals and approved evidence indicate "+c.riskLevel.toLowerCase()+" risk.",c.riskLevel,c.deterministicScore,signals.stream().map(x->value(x,"code")+": "+value(x,"description")).toList(),evidence,citations,List.of("Verified customer contact outcome","Authoritative device reputation"),action,c.deterministicScore>=70?.91:c.deterministicScore>=40?.72:.82,List.of("Seeded policy corpus is current","Mock LLM mode; no external model call"),!"APPROVE".equals(action));c.recommendedAction=action;jdbc.update("UPDATE ai_investigations SET response_json=? WHERE id=?",safeJson(result),investigation);audit.log(actor,"AI_INVESTIGATION_COMPLETED","CASE",caseId.toString(),"recommendation="+action);return result;}
 private Object value(Map<String,Object> map,String key){return map.entrySet().stream().filter(e->e.getKey().equalsIgnoreCase(key)).map(Map.Entry::getValue).findFirst().orElse("");}
 private String safeJson(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){return "{\"error\":\"serialization\"}";}}
 public String validateModelOutput(UUID caseId,String actor,String output){return security.assertSafeOutput(caseId,actor,output);}
}
