apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: mini-risk
spec:
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mini-risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: mini-nasdaq-risk/api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: risk-platform-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
