apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: mini-risk
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: history-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  namespace: mini-risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: mini-nasdaq-risk/history-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: risk-platform-config
            - secretRef:
                name: risk-platform-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
