apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: mini-risk
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: risk-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
  namespace: mini-risk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
    spec:
      containers:
        - name: risk-service
          image: mini-nasdaq-risk/risk-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: risk-platform-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
