data "aws_availability_zones" "available" { state = "available" }
module "vpc" { source = "terraform-aws-modules/vpc/aws" version = "5.21.0" name = "${var.name}-${var.environment}" cidr = "10.20.0.0/16" azs = slice(data.aws_availability_zones.available.names,0,3) private_subnets = ["10.20.0.0/20","10.20.16.0/20","10.20.32.0/20"] public_subnets = ["10.20.128.0/24","10.20.129.0/24","10.20.130.0/24"] enable_nat_gateway = true single_nat_gateway = var.environment != "prod" enable_dns_hostnames = true }
resource "aws_security_group" "data" { name = "${var.name}-data" vpc_id = module.vpc.vpc_id ingress { from_port=5432 to_port=5432 protocol="tcp" cidr_blocks=[module.vpc.vpc_cidr_block] } ingress { from_port=6379 to_port=6379 protocol="tcp" cidr_blocks=[module.vpc.vpc_cidr_block] } egress { from_port=0 to_port=0 protocol="-1" cidr_blocks=["0.0.0.0/0"] } }
resource "random_password" "db" { length=24 special=true }
resource "aws_db_subnet_group" "this" { name=var.name subnet_ids=module.vpc.private_subnets }
resource "aws_db_instance" "orders" { identifier="${var.name}-${var.environment}" engine="postgres" engine_version="16" instance_class="db.t4g.micro" allocated_storage=20 max_allocated_storage=100 db_name="orders" username=var.db_username password=random_password.db.result db_subnet_group_name=aws_db_subnet_group.this.name vpc_security_group_ids=[aws_security_group.data.id] multi_az=var.environment=="prod" backup_retention_period=7 storage_encrypted=true publicly_accessible=false skip_final_snapshot=var.environment!="prod" deletion_protection=var.environment=="prod" }
resource "aws_elasticache_subnet_group" "this" { name=var.name subnet_ids=module.vpc.private_subnets }
resource "aws_elasticache_replication_group" "orders" { replication_group_id="${var.name}-${var.environment}" description="Order read cache" node_type="cache.t4g.micro" port=6379 parameter_group_name="default.redis7" subnet_group_name=aws_elasticache_subnet_group.this.name security_group_ids=[aws_security_group.data.id] automatic_failover_enabled=var.environment=="prod" num_cache_clusters=var.environment=="prod" ? 2 : 1 at_rest_encryption_enabled=true transit_encryption_enabled=true }
resource "aws_msk_serverless_cluster" "events" { cluster_name="${var.name}-${var.environment}" vpc_config { subnet_ids=module.vpc.private_subnets security_group_ids=[aws_security_group.data.id] } client_authentication { sasl { iam { enabled=true } } } }
resource "aws_ecr_repository" "app" { name=var.name image_scanning_configuration { scan_on_push=true } encryption_configuration { encryption_type="AES256" } }
resource "aws_s3_bucket" "audit" { bucket="${var.name}-${var.environment}-${data.aws_caller_identity.current.account_id}" }
resource "aws_s3_bucket_versioning" "audit" { bucket=aws_s3_bucket.audit.id versioning_configuration { status="Enabled" } }
data "aws_caller_identity" "current" {}
