CREATE DATABASE orders;
CREATE DATABASE risk;
CREATE DATABASE history;

GRANT ALL PRIVILEGES ON DATABASE orders TO risk;
GRANT ALL PRIVILEGES ON DATABASE risk TO risk;
GRANT ALL PRIVILEGES ON DATABASE history TO risk;

