apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - base/configmap.yaml
  - base/secret.yaml
  - data/postgres.yaml
  - apps/history-service.yaml
  - apps/risk-service.yaml
  - apps/notification-service.yaml
  - apps/order-service.yaml
  - apps/api-gateway.yaml
  - base/ingress.yaml
